language: go
go_import_path: github.com/neo9/mongodb-backups

cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$GOPATH/pkg/mod"

services:
- docker

go:
- 1.12.x

env:
- GO111MODULE="on"

script:
- set -e;
  go mod vendor;
  go test ./pkg/utils/;
  go build -o ./mongodb-backup-linux-amd64 ./cmd;
  ./ci/release.sh

deploy:
  provider: releases
  api_key:
    secure: g9Jm3tXfQcIT+4aTVgfGFeumzZp7E3ifQtRPZpjXWtTunjzi1dvmLcU9WlbM5vg9e/0ZQo36kLOkmWqfUZain65KCSDW9daJg20/C3gQdk+qZzghkroHbPLs+5A1n98Kr0cRo+eGcfYPKw6oavx6vTuv/aoQvuHDHUN4e5qOIkEeiZgQ2zGIrJQ5bnwdi6hrLMiWNqJ/jFkUb4iGzb+VZryqMTGiiWLkUigj77G1KDfOv1QvQw6ZAwZ9NjSRwmX49//kr2ChKkDuEO5LYC+I+uv8D6uivK/v4yt53DIDV1IoLrRMh3lvM88TbHI0KccZm6M6pA7UuBRZnKk0l6J4tk7L1hLfqo0SlGBR7T1IE2pSBgovgo0xXS12yLW8TED7bte5qFbg2ral2GkJm6z4yuHR9fbdUBdXralRSSE1mF1gl2nQSYplNIicVBn3r19TnMZpxHMhjJ84Dso+cAeSq4aMsUR63z4dDPZ6jcBAh9hYgX3iP7VFoXxx+TjrL45oNvjCh5KcaULqJSUmGi+3z4+x/c+Fms+9rAfrdzyGvXgIhVIs1ch0+u8+YVIal+F+qNUuFrfbqs/1GyRIMOGy3Yrtsl8fJsxVvqsA0RyGDQuHVk0HtEV8i7mkidpjdx41DxoIXgTMsDTolpwTfGXBoruWID1Mcl//RI7jSGq53Ls=
  file: "./mongodb-backup-linux-amd64"
  skip_cleanup: true
  on:
    tags: true
